 default:
   image: ubuntu:focal

 variables:
  SDK_VERSION: 1.7.0

 build-job:
  stage: build
  script:
    - apt-get update && apt-get install -y  default-jdk maven unzip dialog sshpass curl
    - ./.github/actions/build_urcap/entrypoint.sh
